<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Place order</name>
   <tag></tag>
   <elementGuidId>43919921-ae54-48ef-873d-534f4a8a29e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='place_order']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#place_order</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c328654a-9f63-45cb-897d-2614e50ebb11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>951e814f-5cce-45c4-aa2a-1bd1a1b32be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button alt</value>
      <webElementGuid>698ff607-4224-4ce8-99c0-39a4f0480ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>woocommerce_checkout_place_order</value>
      <webElementGuid>cbe8f639-cb07-4c27-9a18-e2b8f1966ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>place_order</value>
      <webElementGuid>eac5c98f-9651-4227-a6df-b6906dfc2b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Place order</value>
      <webElementGuid>e573296c-0b52-4a4a-a6cd-71013095a015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Place order</value>
      <webElementGuid>96e06217-01ff-44a1-b796-db3b8d8ddfa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Place order</value>
      <webElementGuid>51666dce-64ad-4e90-9348-78d4f0612210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;place_order&quot;)</value>
      <webElementGuid>e61ff198-5360-4295-861a-76af4fb1b6a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='place_order']</value>
      <webElementGuid>b8154f15-03db-4d80-880a-98ed4a58bc44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/div/button</value>
      <webElementGuid>bea5a358-6e82-474c-bd68-6bc442c36cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Xendit Docs'])[1]/following::button[1]</value>
      <webElementGuid>25ee69cc-d0bc-4895-93f4-a01e503298ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credit Card (Xendit)'])[1]/following::button[1]</value>
      <webElementGuid>43cf8e2b-a833-49b7-b6ce-75b94531f7ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newsletter'])[1]/preceding::button[1]</value>
      <webElementGuid>00ebc43f-716e-42c9-b0ef-0f84df6cd728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Place order']/parent::*</value>
      <webElementGuid>4e43c7f8-f035-45af-97e3-74e814e3c360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>e5ae1f32-3702-4c97-b72d-d496278f99ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'woocommerce_checkout_place_order' and @id = 'place_order' and (text() = 'Place order' or . = 'Place order')]</value>
      <webElementGuid>365cf959-58b3-453e-9143-e191b0126d54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
